# Generated by Django 5.1.4 on 2025-02-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='name',
        ),
    ]
