# Generated by Django 5.1.4 on 2025-02-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_api', '0002_remove_textbook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
